services:
  - type: web
    name: sms-fraud-ml-service
    env: python
    buildCommand: pip install --upgrade pip wheel setuptools && pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: PIP_NO_CACHE_DIR
        value: "1"